### ISSUE TITLE
Home page in Help->About menu is returning a 404 Page not found error.

### ISSUE THREAD

**Issue by martinbra** [gbmhunter/NinjaTerm#226]
![image](https://user-images.githubusercontent.com/29928669/96505711-e8e33f00-122c-11eb-9795-91475d7c599b.png)

The above about menu links to http://mbedded-ninja.github.io/NinjaTerm/ which is returning a 404 Page not found error. 
I think that http://gbmhunter.github.io/NinjaTerm/ is the correct one.
Maybe one's could also update the copyright dates.

**Comment by gbmhunter** [comment]
@martinbra thanks for the observation! In all honesty, I haven't given this project the love it needs in the last few years! I see you've forked the repo and made the fix, if you submit a pull-request I'll approve it to get in merged into this repo if you want.

**Comment by martinbra** [comment]
I tried a pull request but it didn't pass the compilation because I did not compiled locally, updated version, etc. Can you do it?
